<?php

// tipo de idioma
$tipo_idioma_sistema_usando = $idioma_disponivel[0];

// semana
$semana_idioma = array(
'0' => 'Domingo', 
'1' => 'Segunda-Feira',
'2' => 'Terça-Feira',
'3' => 'Quarta-Feira',
'4' => 'Quinta-Feira',
'5' => 'Sexta-Feira',
'6' => 'Sábado'
);

// mes
$mes_extenso_idioma = array(
'Jan' => 'Janeiro',
'Feb' => 'Fevereiro',
'Mar' => 'Março',
'Apr' => 'Abril',
'May' => 'Maio',
'Jun' => 'Junho',
'Jul' => 'Julho',
'Aug' => 'Agosto',
'Nov' => 'Novembro',
'Sep' => 'Setembro',
'Oct' => 'Outubro',
'Dec' => 'Dezembro'
);

// idioma
$idioma[0] = "Nome deste site";
$idioma[1] = "Descrição deste site";
$idioma[2] = "Cadastro ou login";
$idioma[3] = "Cadastro_login";
$idioma[4] = "Logar";
$idioma[5] = "E-mail";
$idioma[6] = "Senha";
$idioma[7] = "Logar em sua conta ou criar uma nova";
$idioma[8] = "Palavras chaves, separe-as com vírgula (Bolo, fubá, etc...)";
$idioma[9] = "Autor do site";
$idioma[10] = "Este e-mail já está sendo usado, tente outro e-mail.";
$idioma[11] = "E-mail inválido";
$idioma[12] = "Tamanho mínimo da senha ".TAMANHO_MINIMO_SENHA." caracteres";
$idioma[13] = "Este usuário não existe.";
$idioma[14] = "Inicio";
$idioma[15] = "Sair";
$idioma[16] = "E-mail para contato";
$idioma[17] = "<<";
$idioma[18] = "Administrador";
$idioma[19] = "Postar";
$idioma[20] = "Cadastro";
$idioma[21] = "Adicionar categoria";
$idioma[22] = "Criar menus";
$idioma[23] = "Opções de rodapé widget";
$idioma[24] = "Mensagem de subrodapé";
$idioma[25] = "Adicionar bloco";
$idioma[26] = "Adicionar bloco de topo";
$idioma[27] = "Galeria de álbuns";
$idioma[28] = "Galeria de imagens";
$idioma[29] = "Livro de ocorrências";
$idioma[30] = "Contato";
$idioma[31] = "ed_campo_1";
$idioma[32] = "ed_campo_2";
$idioma[33] = "ed_campo_3";
$idioma[34] = "ed_campo_4";
$idioma[35] = "ed_campo_5";
$idioma[36] = "ed_campo_6";
$idioma[37] = "ed_campo_7";
$idioma[38] = "ed_campo_8";
$idioma[39] = "ed_campo_9";
$idioma[40] = "ed_campo_10";
$idioma[41] = "ed_campo_11";
$idioma[42] = "ed_campo_12";
$idioma[43] = "Título";
$idioma[44] = "Conteúdo da publicação";
$idioma[45] = "Publicar";
$idioma[46] = "Carregar imagens...";
$idioma[47] = "Slideshow";
$idioma[48] = "Selecionar imagens...";
$idioma[49] = "Selecione as imagens do slideshow.";
$idioma[50] = "Selecionar áudios...";
$idioma[51] = "Selecionar vídeos...";
$idioma[52] = "Voltar";
$idioma[53] = "Avançar";
$idioma[54] = "Adicione uma descrição";
$idioma[55] = "Voltar...";
$idioma[56] = "Publicação, Página";
$idioma[57] = "Salvar";
$idioma[58] = "Tipo: ";
$idioma[59] = "Páginas";
$idioma[60] = "Publicações";
$idioma[61] = "Orçamento";
$idioma[62] = "Deseja contratar nossos serviços, então faça um orçamento conosco.";
$idioma[63] = "Escreva em detalhes qual serviço você deseja contratar.";
$idioma[64] = "Mensagem de orçamento";
$idioma[65] = "Orçamento da empresa ";
$idioma[66] = "Widget central";
$idioma[67] = "Comentário com Disqus";
$idioma[68] = "Relacionados";
$idioma[69] = "Novidades";
$idioma[70] = "Somente o administrador tem acesso a este recurso!";
$idioma[71] = "Colaborador";
$idioma[72] = "ed_servico_1";
$idioma[73] = "ed_servico_2";
$idioma[74] = "ed_servico_3";
$idioma[75] = "ed_servico_4";
$idioma[76] = "ed_servico_5";
$idioma[77] = "ed_servico_6";
$idioma[78] = "ed_servico_7";
$idioma[79] = "ed_servico_8";
$idioma[80] = "ed_servico_9";
$idioma[81] = "ed_servico_10";
$idioma[82] = "Anúncio de postagem";
$idioma[83] = "Código html do seu anúncio.";
$idioma[84] = "Postagem ou página";
$idioma[85] = "Cor da categoria exemplo #333333";
$idioma[86] = "Salvar cor";
$idioma[87] = "Url de link";
$idioma[88] = "ed_campo_16";
$idioma[89] = "Widget de post";
$idioma[90] = "Você deseja excluir esta imagem para sempre?";
$idioma[91] = "Nome";
$idioma[92] = "Postagem sem título";
$idioma[93] = null;
$idioma[94] = null;
$idioma[95] = null;
$idioma[96] = null;
$idioma[97] = null;
$idioma[98] = "Excluir";
$idioma[99] = "Editar";
$idioma[100] = null;
$idioma[101] = "Sim";
$idioma[102] = null;
$idioma[103] = null;
$idioma[104] = null;
$idioma[105] = null;
$idioma[106] = null;
$idioma[107] = null;
$idioma[108] = "Recortar imagem";
$idioma[109] = null;
$idioma[110] = null;
$idioma[111] = "Excluir esta publicação?";
$idioma[112] = "Atualizar publicação";
$idioma[113] = "Adicionar imagem...";
$idioma[114] = "Excluir imagem?";
$idioma[115] = "Excluir imagem de slideshow?";
$idioma[116] = "Entre em contato conosco";
$idioma[117] = "E-mail ou telefone";
$idioma[118] = "Escreva sua mensagem";
$idioma[119] = "Enviar mensagem";
$idioma[120] = "Desenvolvido por ";
$idioma[121] = "Copyright ";
$idioma[122] = null;
$idioma[123] = null;
$idioma[124] = null;
$idioma[125] = null;
$idioma[126] = null;
$idioma[127] = null;
$idioma[128] = null;
$idioma[129] = null;
$idioma[130] = null;
$idioma[131] = null;
$idioma[132] = "Editar perfil";
$idioma[133] = "Endereço";
$idioma[134] = "Cidade";
$idioma[135] = "Estado";
$idioma[136] = "Telefone";
$idioma[137] = null;
$idioma[138] = "Usuário";
$idioma[139] = "Bate-papo:";
$idioma[140] = "On-line";
$idioma[141] = "Off-line";
$idioma[142] = "Escreva e pressione enter.";
$idioma[143] = "Histórico";
$idioma[144] = "Histórico de conversas";
$idioma[145] = "Carregar mais...";
$idioma[146] = "Excluir esta conversa?";
$idioma[147] = "Fechar";
$idioma[148] = "Pesquisar";
$idioma[149] = "Alterar imagem...";
$idioma[150] = "Mudar senha";
$idioma[151] = "Senha atual";
$idioma[152] = "Nova senha";
$idioma[153] = "Confirme a senha";
$idioma[154] = "Excluir conta";
$idioma[155] = "Você não pode excluir a conta do administrador.";
$idioma[156] = "Português";
$idioma[157] = "Inglês";
$idioma[158] = "Recuperar senha";
$idioma[159] = "E-mail e pressione enter";
$idioma[160] = "Sua senha de acesso: ";
$idioma[161] = "Sua senha foi enviada para o email: ";
$idioma[162] = "Widget lateral 1";
$idioma[163] = "Escrito por: ";
$idioma[164] = "Leia mais";
$idioma[165] = "Página inicial";
$idioma[166] = "Telefone: ";
$idioma[167] = "Home";
$idioma[168] = null;
$idioma[169] = null;
$idioma[170] = null;
$idioma[171] = null;
$idioma[172] = null;
$idioma[173] = null;
$idioma[174] = "Editar imagem";
$idioma[175] = "Salvar edição";
$idioma[176] = "Adicionar imagens...";
$idioma[177] = "Cadastros desabilitados";
$idioma[178] = null;
$idioma[179] = "Galeria de imagens";
$idioma[180] = "Carregar mais imagens...";
$idioma[181] = "Enviar imagens para galeria...";
$idioma[182] = "de";
$idioma[183] = "Sobre mim: ";
$idioma[184] = "Sobre mim";
$idioma[185] = "Categorias";
$idioma[186] = "Nome da categoria";
$idioma[187] = "Adicionar categoria";
$idioma[188] = "Vamos criar categorias para publicações.";
$idioma[189] = "Remover categoria";
$idioma[190] = "Excluir esta categoria?";
$idioma[191] = "Escolha uma categoria";
$idioma[192] = "Categoria";
$idioma[193] = "Criar menu";
$idioma[194] = "Título do menu";
$idioma[195] = "Criar";
$idioma[196] = "Link do menu";
$idioma[197] = "Criar submenu";
$idioma[198] = "Título de submenu";
$idioma[199] = "Link de submenu";
$idioma[200] = "Deseja mesmo excluir este item?";
$idioma[201] = "Exclua";
$idioma[202] = "Excluir menu ou item";
$idioma[203] = "Opções de rodapé";
$idioma[204] = "Mensagem de subrodapé";
$idioma[205] = "Construir blocos";
$idioma[206] = "Cadastro";
$idioma[207] = "Título";
$idioma[208] = "Subtítulo";
$idioma[209] = "Adicionar bloco";
$idioma[210] = "Excluir este bloco?";
$idioma[211] = "Deseja mesmo excluir este bloco?";
$idioma[212] = "Copiar endereço";
$idioma[213] = "Blocos do topo";
$idioma[214] = "Conteúdo do bloco";
$idioma[215] = "Atualizar bloco";
$idioma[216] = "Título do álbum";
$idioma[217] = "Criar álbum";
$idioma[218] = "Álbum sem título";
$idioma[219] = "Se você excluir este álbum todas as imagens serão excluídas para sempre, deseja prosseguir?";
$idioma[220] = "Excluir álbum de imagens";
$idioma[221] = "Todas as imagens - ";
$idioma[222] = "Editar widget";
$idioma[223] = "Widget de topo";
$idioma[224] = "ed_campo_13";
$idioma[225] = "Sobre o site";
$idioma[226] = "ed_campo_14";
$idioma[227] = "Enviar imagem...";
$idioma[228] = "Url de link de bloco";
$idioma[229] = "ed_campo_15";
$idioma[230] = null;
$idioma[231] = null;
$idioma[232] = null;
$idioma[233] = null;
$idioma[234] = null;
$idioma[235] = null;
$idioma[236] = null;
$idioma[237] = null;
$idioma[238] = null;
$idioma[239] = null;
$idioma[240] = null;

?>